// Generated by CoffeeScript 1.8.0
(function() {
  var buildBoard, collapseCells, generateTile, getRow, mergeCells, move, moveisValid, printArray, randomCellIndices, randomInt, randomValue, setRow, showBoard;

  randomInt = function(x) {
    return Math.floor(Math.random() * x);
  };

  randomCellIndices = function() {
    return [randomInt(4), randomInt(4)];
  };

  randomValue = function() {
    var values;
    values = [2, 4, 2, 4];
    return values[randomInt(4)];
  };

  buildBoard = function() {
    return [0, 1, 2, 3].map(function() {
      return [0, 1, 2, 3].map((function() {
        return 0;
      }));
    });
  };

  generateTile = function(board) {
    var column, row, value, _ref;
    value = randomValue();
    _ref = randomCellIndices(), row = _ref[0], column = _ref[1];
    console.log("randomInt: " + row + " | " + column);
    if (board[row][column] === 0) {
      board[row][column] = value;
    } else {
      generateTile(board);
    }
    return console.log("generate tile");
  };

  move = function(board, direction) {
    var i, newBoard, row, _i;
    newBoard = buildBoard();
    for (i = _i = 0; _i <= 3; i = ++_i) {
      if (direction === 'right') {
        row = getRow(i, board);
        row = mergeCells(row, direction);
        row = collapseCells(row, direction);
        setRow(row, i, newBoard);
      }
    }
    return newBoard;
  };

  getRow = function(r, board) {
    var row;
    return row = [board[r][0], board[r][1], board[r][2], board[r][3]];
  };

  setRow = function(row, index, board) {
    return board[index] = row;
  };

  mergeCells = function(row, direction) {
    var a, b, _i, _j, _ref;
    if (direction === 'right') {
      for (a = _i = 3; _i > 0; a = --_i) {
        for (b = _j = _ref = a - 1; _ref <= 0 ? _j <= 0 : _j >= 0; b = _ref <= 0 ? ++_j : --_j) {
          if (row[a] === 0) {
            break;
          } else if (row[a] === row[b]) {
            row[a] *= 2;
            row[b] = 0;
            break;
          } else if (row[b] !== 0) {
            break;
          }
        }
      }
    }
    return row;
  };

  collapseCells = function(row, direction) {
    row = row.filter(function(x) {
      return x !== 0;
    });
    if (direction === 'right') {
      while (row.length < 4) {
        row.unshift(0);
      }
    }
    return row;
  };

  console.log(collapseCells([0, 2, 4, 2], 'right'));

  moveisValid = function(orignalBoard, newBoard) {
    var answer, col, row, _i, _j;
    answer = true;
    for (row = _i = 0; _i <= 3; row = ++_i) {
      for (col = _j = 0; _j <= 3; col = ++_j) {
        if (orignalBoard[row][col] !== newBoard[row][col]) {
          return true;
        }
      }
    }
    return false;
  };

  showBoard = function(board) {
    var col, row, _i, _results;
    _results = [];
    for (row = _i = 0; _i <= 3; row = ++_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (col = _j = 0; _j <= 3; col = ++_j) {
          _results1.push($(".r" + row + ".c" + col + " > div").html(board[row][col]));
        }
        return _results1;
      })());
    }
    return _results;
  };

  printArray = function(array) {
    var row, _i, _len;
    console.log("-- Start --");
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      row = array[_i];
      console.log(row);
    }
    return console.log("-- End--");
  };

  $(function() {
    this.board = buildBoard();
    generateTile(this.board);
    generateTile(this.board);
    printArray(this.board);
    showBoard(this.board);
    return $('body').keydown((function(_this) {
      return function(e) {
        var direction, key, keys, newBoard;
        e.preventDefault();
        key = e.which;
        keys = [37, 38, 39, 40];
        if ((keys.indexOf(key)) > -1) {
          console.log("key: ", key);
          direction = (function() {
            switch (key) {
              case 37:
                return 'left';
              case 38:
                return 'up';
              case 39:
                return 'right';
              case 40:
                return 'down';
            }
          })();
          newBoard = move(_this.board, direction);
          printArray(newBoard);
          if (moveisValid(_this.board, newBoard)) {
            console.log("valid");
            _this.board = newBoard;
            generateTile(_this.board);
            return showBoard(_this.board);
          } else {
            return console.log("invalid");
          }
        } else {

        }
      };
    })(this));
  });

}).call(this);

//# sourceMappingURL=main.js.map
